# Basic

In [1]:
import numpy as np
import pandas as pd

In [2]:
space_data = {
    "Mission": ["Chandrayaan-3", "Gaganyaan", "Aditya-L1", "RISAT-2B"],
    "Type": ["Lunar", "Human Spaceflight", "Solar Study", "Surveillance"],
    "Country": ["India", "India", "India", "India"],
    "Status": ["Success", "Upcoming", "Ongoing", "Active"],
    "Budget (Cr)": [615, 10000, 400, 800]
}

In [3]:
df = pd.DataFrame(space_data)

In [4]:
print("🚀 Space Mission Data:")
df

🚀 Space Mission Data:

         Mission               Type Country    Status  Budget (Cr)
0  Chandrayaan-3              Lunar   India   Success          615
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000
2      Aditya-L1        Solar Study   India   Ongoing          400
3       RISAT-2B       Surveillance   India    Active          800

In [5]:
df.to_csv('Space_data.csv')

In [6]:

print("\n✅ Successful Missions:")
print(df[df["Status"] == "Success"])


print("\n💰 Sorted by Budget:")
print(df.sort_values(by="Budget (Cr)", ascending=False))


print("\n📊 Average Budget:")
print(df["Budget (Cr)"].mean())

✅ Successful Missions:
         Mission   Type Country   Status  Budget (Cr)
0  Chandrayaan-3  Lunar   India  Success          615

💰 Sorted by Budget:
         Mission               Type Country    Status  Budget (Cr)
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000
3       RISAT-2B       Surveillance   India    Active          800
0  Chandrayaan-3              Lunar   India   Success          615
2      Aditya-L1        Solar Study   India   Ongoing          400

📊 Average Budget:
2953.75

In [7]:
df.head(2)

         Mission               Type Country    Status  Budget (Cr)
0  Chandrayaan-3              Lunar   India   Success          615
1      Gaganyaan  Human Spaceflight   India  Upcoming        10000

In [8]:
df.tail(2)

     Mission          Type Country   Status  Budget (Cr)
2  Aditya-L1   Solar Study   India  Ongoing          400
3   RISAT-2B  Surveillance   India   Active          800

In [9]:
df.describe()

        Budget (Cr)
count      4.000000
mean    2953.750000
std     4700.342851
min      400.000000
25%      561.250000
50%      707.500000
75%     3100.000000
max    10000.000000

In [12]:
df = pd.read_csv('solar_system.csv')

In [13]:
df

,Name,Type,Planet,Distance_from_Sun_km,Radius_km,Mass_kg,Gravity_m_s2,Orbital_Period_days,Moons
0,Mercury,Planet,Sun,57900000,2439,3.300000e+23,3.7000,88.0,0
1,Venus,Planet,Sun,108200000,6051,4.870000e+24,8.8700,225.0,0
2,Earth,Planet,Sun,149600000,6371,5.970000e+24,9.8000,365.0,1
3,Mars,Planet,Sun,227900000,3389,6.420000e+23,3.7100,687.0,2
4,Jupiter,Planet,Sun,778500000,69911,1.900000e+27,24.7900,4333.0,95
5,Saturn,Planet,Sun,1434000000,58232,5.680000e+26,10.4400,10759.0,146
6,Uranus,Planet,Sun,2871000000,25362,8.680000e+25,8.6900,30687.0,27
7,Neptune,Planet,Sun,4495000000,24622,1.020000e+26,11.1500,60190.0,14
8,Moon,Moon,Earth,384400,1737,7.350000e+22,1.6200,27.0,0
9,Phobos,Moon,Mars,9376,11,1.070000e+16,0.0057,0.3,0
10,Deimos,Moon,Mars,23463,6,1.480000e+15,0.0030,1.3,0
11,Europa,Moon,Jupiter,670900,1560,4.800000e+22,1.3100,3.5,0
12,Ganymede,Moon,Jupiter,1070400,2634,1.480000e+23,1.4300,7.1,0
13,Callisto,Moon,Jupiter,1882700,2410,1.080000e+23,1.2400,16.7,0
14,Titan,Moon,Saturn,1221870,2575,1.350000e+23,1.3500,16.0,0
15,Enceladus,Moon,Saturn,238000,252,1.080000e+20,0.1130,1.4,0
16,Triton,Moon,Neptune,354800,1353,2.140000e+22,0.7800,5.9,0
17,Pluto,Dwarf Planet,Sun,5906000000,1188,1.310000e+22,0.6200,90560.0,5
18,Ceres,Dwarf Planet,Asteroid Belt,413700000,473,9.390000e+20,0.2700,1680.0,0
19,Haumea,Dwarf Planet,Kuiper Belt,6452000000,816,4.010000e+21,0.4400,103774.0,2
20,Makemake,Dwarf Planet,Kuiper Belt,6850000000,715,3.100000e+21,0.5000,112897.0,1
21,Eris,Dwarf Planet,Kuiper Belt,10100000000,1163,1.660000e+22,0.8200,203830.0,1